### ISSUE TITLE
FormExternalConfiguration and hierarchical viewmodel

### ISSUE THREAD

**Issue by wald-tq** [AngularAgility/AngularAgility#131]
I have a hierarchical viewmodel for my form:

$scope.formValues containing for example

* `$scope.formValues.Name`
* `$scope.formValues.Email`
* `$scope.formValues.Department`

Then I have nested two Addresses:
`$scope.formValues.CompanyAddress`
`$scope.formValues.HomeAddress`
which each contain things like:
* Street
* Town

I couldn't figure out how to leverage formExternalConfiguration for the validation of the Address forms. I think this would be a nice use-case for formExternalConfiguration. 

Validation for the main form works. But it doesn't work for the two Address forms. Is it a requirement to have a flat view model for Angular Agility?

**Comment by johnculviner** [comment]
@rolandzwaga any thoughts on this one? Otherwise I would just recommend using manual forms for the edge cases (you can nest + repeat forms as you can see in this example http://angularagility.herokuapp.com/#/formExtensions/formExtensions/advanced)

**Comment by wald-tq** [comment]
Based on the code from AngularAgility I created my own, simpler directive for external form configuration: https://gist.github.com/wald-tq/b10467c920efe2d5d3cc

The key part of my directive is the function `Object.byString()` which gets a value out of a object by using a string.
```
validations:
  Address:
    City: {ng-maxlength: "5", ng-maxlength-msg: "City cannot be more than 5 characters."}
      Street: {
        ng-maxlength: "15"
        ng-maxlength-msg: "Street cannot be more than 15 characters."
        required: true
        required-msg: "Street is required."
      CreditCard: {,…}
        ng-pattern: "/^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\d{3})\d{11})$/"
        ng-pattern-msg: "CreditCard is an invalid credit card number."
```
now I can get the validation for the input
```HTML
<input ng-model="model.Address.Street" />
```
with: `Object.byString(validations, "Address.Street");` which is quite cool I think.
